---
- ansible.builtin.import_playbook: machine-hypervisor.yml
- ansible.builtin.import_playbook: image-gateway.yml
- ansible.builtin.import_playbook: template-to-machine.yml
  vars:
    host_to_start: gateway.build.example.com
- ansible.builtin.import_playbook: image-id.yml
- ansible.builtin.import_playbook: template-to-machine.yml
  vars:
    host_to_start: id.build.example.com
- ansible.builtin.import_playbook: image-satellite.yml
- ansible.builtin.import_playbook: satellite-install.yml
- ansible.builtin.import_playbook: satellite-content.yml
- ansible.builtin.import_playbook: satellite-lifecycle.yml
- ansible.builtin.import_playbook: satellite-provision.yml
- ansible.builtin.import_playbook: machine-to-template.yml
  vars:
    host_to_image: satellite.build.example.com
- ansible.builtin.import_playbook: template-to-machine.yml
  vars:
    host_to_start: satellite.build.example.com
# Ansible Automation Platform Private Automation Hub
- ansible.builtin.import_playbook: vm-kickstart.yml
  vars:
    host_to_build: aaphub.build.example.com
- ansible.builtin.import_playbook: aaphub-roles.yml

