---
# !!! move to collection roles

# a simpler version of the far superior 
# https://github.com/sscheib/ansible_satellite
#
# manually created subscription allocation
# https://access.redhat.com/management/subscription_allocations/db350766-32e5-4713-8789-d40dfbe9c969
# subscription allocation can be created using API
# https://access.redhat.com/solutions/6981907
# How to create subscription allocation using the RHSM API?

- name: Satellite config 
  hosts: satellite
  gather_facts: true  # required for the role redhat.satellite_operations.installer
  become: true  # required for the role redhat.satellite_operations.installer
  vars_files:
    - ~/vault-credentials.yml
  environment:
    http_proxy: "http://gateway.{{ lab_domain }}:3128"
    HTTPS_PROXY: "http://gateway.{{ lab_domain }}:3128"
    no_proxy: localhost,127.0.0.1,example.com
  roles:

      # 4
      # https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/role/manifest/
    - role: redhat.satellite.manifest
      vars:
        satellite_server_url: "https://{{ inventory_hostname }}"
        satellite_username: "{{ sat_admin_user }}"
        satellite_password: "{{ sat_admin_pass }}"
        satellite_organization: "Default Organization"
        satellite_manifest_path: "~/manifest.zip"
        satellite_manifest_download: true
        satellite_rhsm_username: "{{ rhsm_user }}"
        satellite_rhsm_password: "{{ rhsm_password }}"
        satellite_manifest_uuid: "db350766-32e5-4713-8789-d40dfbe9c969"

      # 6
    - role: redhat.satellite.repositories
      vars:
        satellite_server_url: "https://{{ inventory_hostname }}"
        satellite_username: "{{ sat_admin_user }}"
        satellite_password: "{{ sat_admin_pass }}"
        satellite_organization: "Default Organization"
        satellite_products: "{{ sat_products }}"

  tasks:

      # 7
    # https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/module/repository_sync/
    # better to wait or to do as async background job?
    # https://github.com/sscheib/ansible_satellite/blob/main/07_satellite_sync_repositories.yml
    - name: "Sync all repositories in each product"
      redhat.satellite.repository_sync:
        server_url: "https://{{ inventory_hostname }}"
        username: "{{ sat_admin_user }}"
        password: "{{ sat_admin_pass }}"
        organization: "Default Organization"
        product: "{{ item }}"
      loop: "{{ sat_products | map(attribute='name') | unique }}"

      # 8
      # https://console.redhat.com/ansible/automation-hub/repo/published/redhat/satellite/content/module/sync_plan/
    - name: "Create daily sync plan for all products"
      redhat.satellite.sync_plan:
        name: "Daily Sync"
        server_url: "https://{{ inventory_hostname }}"
        username: "{{ sat_admin_user }}"
        password: "{{ sat_admin_pass }}"
        organization: "Default Organization"
        interval: "daily"    #  hourly, daily, weekly, custom cron
        enabled: true
        # sync_date: "{{ lookup('ansible.builtin.pipe', 'date +\"%Y-%m-%d %H:%M:%S %Z\"') }}"  # now
        # sync_date: "2017-01-01 00:00:00 UTC" # fixed date
        sync_date: "{{ lookup('ansible.builtin.pipe', 'date +\"%Y-%m-%d 10:00:00 %Z\" -d \"+1 day\"') }}"  # 10am tomorrow
        products: "{{ sat_products | map(attribute='name') | list }}"
        state: present

      # 9
      # lifecycle
