---
- name: Configure new server machine
  # hosts: aapcontrol
  # hosts: satellite
  # hosts: id
  hosts: gateway
  # hosts: aaphub
  become: true
  gather_facts: true
  #gather_facts: false
  serial: 1
  vars_files:
    - ~/vault-credentials.yml
  # environment:
  #     http_proxy: "http://gateway.{{ lab_domain }}:3128"
  #     HTTPS_PROXY: "http://gateway.{{ lab_domain }}:3128"
  #     no_proxy: localhost,127.0.0.1,example.com
  #
  roles:
    # - role: nick.app.prometheus_node_exporter
    # - role: nick.platform.insights_client
    # - role: grafana.grafana.grafana
    #   vars:
    #     grafana_security:
    #       admin_user: admin
    #       admin_password: 'Password;1'
    - role: rhel-system-roles.network
      vars:
        network_connections:
          - name: enp2s0
            # state: up
            type: ethernet
            # interface_name: defaults to the connection name
            ip:
              address:
                - "{{ nics[1]['ip'] }}/24"
              route:
                - network: "{{ lab_source_net_prefix }}.0"
                  prefix: 24
                  gateway: "{{ lab_build_net_prefix }}.1"
                # - network: "{{ lab_build_net_prefix }}.0"
                #   prefix: 24
                #   gateway: "{{ lab_build_net_prefix }}.1"
                - network: "{{ lab_supply_net_prefix }}.0"
                  prefix: 24
                  gateway: "{{ lab_build_net_prefix }}.1"
              route_append_only: true
              # dhcp4: false

  tasks:

  - name: Update runtime state from connection profile
    ansible.builtin.shell:
      cmd: nmcli  connection up enp2s0
