---
- name: Configure new server machine
  hosts: monitor
  # hosts: aapcontrol
  # hosts: satellite
  # hosts: id
  # hosts: gateway
  # hosts: aaphub
  become: true
  gather_facts: true
  #gather_facts: false
  serial: 1
  vars_files:
    - ~/vault-credentials.yml
  environment:
      http_proxy: "http://gateway.{{ lab_domain }}:3128"
      HTTPS_PROXY: "http://gateway.{{ lab_domain }}:3128"
      no_proxy: localhost,127.0.0.1,example.com
  #
  roles:
    #- role: nick.app.prometheus_node_exporter
    #- role: nick.platform.insights_client
    - role: grafana.grafana.grafana
      vars:
        grafana_security:
          admin_user: admin
          admin_password: 'Password;1'

