---
# These values override defaults.
# default variables and their values are listed here.
#   https://github.com/nickhardiman/ansible-collection-platform/blob/main/roles/libvirt_machine_kickstart/defaults/main.yml

# virt-install
# default RHEL 9

# compute
cpus: 4
ram: 12288

# Default 4Gb is not enough 
# Even 8G can fail syncing from the huge galaxy.ansible.com repo.
# galaxy sync "Associating Content" causes OOMkiller fun
#   Nov 16 17:31:00 aaphub kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/system-pulpcore\x2dworker.slice/pulpcore-worker@2.service,task=pulpcore-worker,pid=1822,uid=984
#   Nov 16 17:31:00 aaphub kernel: Out of memory: Killed process 1822 (pulpcore-worker) total-vm:2228980kB, anon-rss:2092920kB, file-rss:0kB, shmem-rss:0kB, UID:984 pgtables:4200kB oom_score_adj:0
#   Nov 16 17:31:00 aaphub pulpcore-worker[1700]: pulp [None]: pulpcore.tasking.pulpcore_worker:WARNING: Task process for 5a31e798-14ac-4907-9a4f-15e9a65a2e30 exited with non zero exitcode -9.
# 4G fails the preflight check.
#   collections/ansible_collections/ansible/automation_platform_installer/roles/preflight/defaults/main.yml
#   required_ram: 7400

# storage
# default 30GB disk

# network
# MAC addresses are listed here.
#   https://github.com/nickhardiman/ansible-playbook-build/blob/main/README.adoc
nics:
-
  name: enp1s0
  mac: "{{ lab_mac_prefix }}:00:06"
  net: "{{ lab_libvirt_name }}"
  # !!! get rid of this?
  # used in
  # ansible_collections/nick/platform/roles/hosts_record/tasks/main.yml
  # If interface IP provided by DHCP, prob. shouldnt be here too.
  ip: "{{ lab_net_prefix }}.6"

# firewall
# Command 'firewall-offline-cmd' uses XML files in /usr/lib/firewalld/services/.
net_services:
  - ssh
  - http
  - https
  
# OS
host: aaphub
fqdn: "{{ host }}.{{ lab_domain }}"
RPMs:
  - cockpit

# kickstart
kickstart_template: "kvm-guest-nic-static.ks.j2"
